# This file contains the default parameter configurations that yield the
# figures present in the final version of the paper

DISABLE_DOER: False # if True, bypasses Doer functionality altogether. No calculation will be loaded or saved
DISABLE_STORE: False # if True, disables store functionality. No operator will be loaded or saved

SAVE_FIGURES: True
FIG_DIR: 'default' # where to store figures

# ---- General calculation parameters for the Harmonic oscillator ----
HO_q0: 1 # position of initial state in phase space
HO_p0: 0
HO_s: 0.1 # standard deviation of classical distribution

HO_a: 0.5 # defines how much overlap between the distribution in one step with the next (a=0 max. overlap, a > 1 no overlap)

HO_N_res: 300 # number of points in phase space for the classical distribution. Make sure is enough to resolve packet!
HO_N_sigma_res: 5 # sigmas of space between the packet center (at all times) and limits of the phase-space box.
# this also defines integration limits for calculating the matrix elements of the initial quantum coherent ensemble
# make sure the box includes the whole evolution

HO_fid: 0.999999999 # fidelity of truncated quantum coherent state

HO_figs_1_and_2_n_steps: 200 # number of time-steps for evolution
HO_figs_1_and_2_hbars: [0.0625, 0.0625] #1/32, 1/64, 1/128] # hbars for figs 1 and 2. Tested with 4 values
